### ISSUE TITLE
Software volume control

### ISSUE THREAD

**Issue by sa666666** [6502ts/6502.ts#59]
I don't know how easy/possible this is, but would it be possible to have software volume control in Stellerator.  Currently, every time I test a ROM, the windows in the house shake, since the volume is top high :smiling_imp:

Apologies if this is already possible.  In that case, please advise on how to use it.

**Comment by DirtyHairy** [comment]
That's because you're running the it-goes-to-11-edition :smiling_imp:

Actually, that's a pretty nice suggestion, the unability to control the volume has been bothering me, too. It's also not a difficult thing to do, basically just exposing a browser setting. The only thing that keeps me from doing it straightahead is the reluctance to touch frontend again without refactoring it :smirk: I guess I'll look into this as one of the next things, in particular before dealing with PCM audio #44 .

**Comment by DirtyHairy** [comment]
Implemented in 137fc8c .
