### ISSUE TITLE
Add an indicator to screenshots to indicate whether the time machine was used before taking it

### ISSUE THREAD

**Issue by DirtyHairy** [6502ts/6502.ts#68]

**Comment by ayarusso** [comment]
Some additional thoughts on this.  One of the motivating factors in adding a feature like this is to help authenticate that the game was played without using time machine.  This is useful for high-score contests, such as those that take place on the AtariAge 2600 High Score Club.  

Ideally there would be some visual indicator the user can toggle on/off.  The user would want to toggle it in before taking a screenshot.  The indicator would be used to verify that Time Machine was not used during this particular session.  Session being the time starting from when the current ROM image has been loaded.  

Since people could relatively easily Photoshop a visual indicator onto an image, it would be helpful if the indicator had some type of complexity to it that would make it more difficult to falsify.
